### ISSUE TITLE
integers can be quoted in jsonld 

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/presentation-validator#55] opened 2017-09-15 02:35 UTC
The validator reports an error "Validation Error: sc:Canvas['height'] does not accept a unicode, only an integer" for quoted integers. This is a python issue, and probably not intended.

Json-ld uses type coercion to identify values.  Whether or not a value is quoted does not indicate its type.  See https://www.w3.org/TR/json-ld/#typed-values.  Also, in RDF all literals are quoted, so an fromRDF transformation to JSON-LD would not arbitrarily remove the quotes for an integer.

**Comment by zimeon** [comment] 2017-09-15 18:14
Hmmm... interesting. The [Image API](http://iiif.io/api/image/2.1/#profile-description) spec was written around the idea of the `info.json` being a plain JSON document that it also valid JSON-LD. As such it cannot rely on JSON-LD type coercion. IMO, the spec if not clear that _integer_ means _JSON integer_ (not quoted) even though that was the intention and is the form used in the examples (and the validator is correct according to that intention).

However, we do want it to be possible to create an `info.json` from RDF. So if standard JSON-LD production mechanisms do not allow generation without the quotes then that seems like a spec issue to consider (along with implications for client support). I note that in the demo I did at SWIB last year [I got this wrong (and have quoted integers)](https://github.com/zimeon/iiif-ld-demo/blob/master/image-api/write_image_info.md).

**Comment by azaroth42** [comment] 2017-09-18 21:33
I agree that from a validator perspective this is "working as intended".  We should take the quoted integers specification issue to IIIF/iiif.io to discuss with the broader community.

Propose close wontfix ... and reopen/recreate if there's a change to the spec.

**Closed** 2017-09-19 15:55 UTC
