### ISSUE TITLE
Validator balks at lack of @type on some resources

### ISSUE THREAD

**Issue by blalbrit** [IIIF/presentation-validator#16] opened 2015-09-21 23:40 UTC
There may be a mismatch between spec and validator expectations. Getting an error on a (many) Stanford manifest that every resource must have @type: http://iiif.io/api/presentation/validator/service/validate?url=http%3A%2F%2Fpurl.stanford.edu%2Ffm590rc7316%2Fiiif%2Fmanifest.json&version=2.0&format=html

This seems to derive from the fact that thumbnail lacks @type (?) - but spec shows w/out: http://iiif.io/api/presentation/2.0/#manifest

Which is correct? if not thumbnail, this can be a feature request for more accurate error reporting for missing @type (as in, which resource(s) are missing a required something).

**Comment by azaroth42** [comment] 2015-09-22 15:33
Per http://iiif.io/api/presentation/2.0/#technical-properties:
> "All resources must have a type specified"

So the example is wrong.

**Comment by azaroth42** [comment] 2016-12-09 21:33
Fixed in underlying lib (dupe of previous) to allow no @type on thumbnails, as it's clearly an image

**Closed by azaroth42** 2016-12-09 21:33 UTC
